// <auto-generated />
using System;
using Anade.Khadamat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anade.Khadamat.Data.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20260405091841_Add_MoisCloture")]
    partial class Add_MoisCloture
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.Activite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgenceWilayaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateActivite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lieu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("NombreVisiteurs")
                        .HasColumnType("int");

                    b.Property<string>("Organisateurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Participants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StructureId")
                        .HasColumnType("int");

                    b.Property<string>("Sujet")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TypeActiviteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("structureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("structureDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgenceWilayaId");

                    b.HasIndex("TypeActiviteId");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteForum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActiviteForums");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteJourneeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActiviteJourneeInfos");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActivitePresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.Property<string>("Media")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActivitePresses");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteRadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.Property<string>("Intervenants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationRadio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActiviteRadios");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteReunionExterne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActiviteReunionExternes");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActiviteSalons");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteTelevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.Property<string>("ChaineTV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("ActiviteTVs");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.AgenceWilaya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgenceWilayas");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.MoisCloture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("CloturePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCloture")
                        .HasColumnType("bit");

                    b.Property<int>("Mois")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Annee", "Mois")
                        .IsUnique();

                    b.ToTable("MoisClotures");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.TypeActivite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeActivite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.Activite", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.AgenceWilaya", "AgenceWilaya")
                        .WithMany("Activities")
                        .HasForeignKey("AgenceWilayaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anade.Khadamat.Domain.Entity.TypeActivite", "TypeActivite")
                        .WithMany()
                        .HasForeignKey("TypeActiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgenceWilaya");

                    b.Navigation("TypeActivite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteForum", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activiteForums")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteJourneeInfo", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activiteJournesInfos")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActivitePresse", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activitePresse")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteRadio", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activiteRadio")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteReunionExterne", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activiteReunionExterne")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteSalon", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activiteSalon")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.ActiviteTelevision", b =>
                {
                    b.HasOne("Anade.Khadamat.Domain.Entity.Activite", "Activite")
                        .WithMany("activiteTelevision")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.Activite", b =>
                {
                    b.Navigation("activiteForums");

                    b.Navigation("activiteJournesInfos");

                    b.Navigation("activitePresse");

                    b.Navigation("activiteRadio");

                    b.Navigation("activiteReunionExterne");

                    b.Navigation("activiteSalon");

                    b.Navigation("activiteTelevision");
                });

            modelBuilder.Entity("Anade.Khadamat.Domain.Entity.AgenceWilaya", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
